apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud_luizalabs_byron
spec:
  selector:
    matchLabels:
      app: crud_luizalabs_byron
  replicas: 3
  template:
    metadata:
      labels:
        app: crud_luizalabs_byron
    spec:
      containers:
        - name: crud_luizalabs_byron
          image: elizaoliveria/crud_luizalabs_byron
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000