# Generated by Django 3.2.7 on 2021-09-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpId', models.PositiveBigIntegerField()),
                ('cmpCnpj', models.CharField(max_length=16)),
                ('cmpName', models.CharField(max_length=50)),
                ('cmpPassword', models.CharField(max_length=20)),
                ('cmpAddress', models.CharField(max_length=50)),
                ('cmpEmail', models.CharField(max_length=20)),
                ('cmpPhone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodId', models.PositiveBigIntegerField()),
                ('prodName', models.CharField(max_length=50)),
                ('prodCompany', models.CharField(max_length=50)),
                ('prodDescription', models.CharField(max_length=200)),
                ('prodPrice', models.FloatField()),
            ],
        ),
    ]
